export { default as Home } from "./Home"
export { default as About } from "./About"
export { default as Projects} from "./Projects"
export { default as Demos} from "./Demos"
export { default as Blog} from "./Blog"
export { default as ContactMe } from "./ContactMe"